In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

import torch
import torch.optim as optim
import torch.nn as nn
#from torchviz import make_dot

Here are some examples of data.

In [2]:
scalar = torch.tensor(3.14159) 
vector = torch.tensor([1, 2, 3]) 
matrix = torch.ones((2, 3), dtype=torch.float) 
tensor = torch.randn((2, 3, 4), dtype=torch.float)

- [torch.zeros](https://pytorch.org/docs/stable/torch.html)
- [torch.ones](https://pytorch.org/docs/stable/generated/torch.ones.html?highlight=ones#torch.ones)
- [torch.randn](https://pytorch.org/docs/stable/generated/torch.randn.html#torch.randn)
  - randn returns tensor with random values with M = 0 and SD = 1.
- [torch.rand](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand)
  - returns tensor with random values with uniform distribution from 0 to 1.
- [torch.randint](https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint)
  - random integers generated uniformly between low (inclusive) and high (exclusive).



In [3]:
rand_int = torch.randint(3, 10, (5,5), dtype = torch.int)
print(rand_int)
rand_int = torch.randint(3, 100, (5,5), dtype = torch.int)
print(rand_int)
rand_int = torch.randint(100, 300, (5,5), dtype = torch.int)
print(rand_int)

tensor([[7, 5, 7, 3, 3],
        [9, 8, 8, 8, 3],
        [9, 4, 8, 3, 5],
        [6, 6, 4, 9, 3],
        [4, 9, 9, 4, 3]], dtype=torch.int32)
tensor([[52, 32, 50, 86, 80],
        [20, 92, 26, 15, 29],
        [62, 38, 93,  4, 60],
        [91, 77, 66, 47, 98],
        [16, 36, 59, 51, 60]], dtype=torch.int32)
tensor([[180, 246, 180, 229, 126],
        [270, 160, 288, 143, 207],
        [266, 199, 280, 232, 201],
        [225, 181, 284, 128, 147],
        [162, 290, 230, 206, 150]], dtype=torch.int32)


In [4]:
rand = torch.rand((5,5,))
rand

tensor([[0.0523, 0.4096, 0.2072, 0.6050, 0.9379],
        [0.0871, 0.4755, 0.9953, 0.2843, 0.6266],
        [0.1279, 0.7835, 0.7402, 0.8152, 0.1690],
        [0.8373, 0.7029, 0.1886, 0.6162, 0.3675],
        [0.6531, 0.8747, 0.7497, 0.5858, 0.3085]])

In [5]:
rand_norm = torch.randn((5,5))
print(rand_norm)
print(rand_norm.shape, rand_norm.size())

tensor([[-1.3821e-01,  1.0823e-03, -9.2208e-01,  2.2910e-01, -5.9043e-01],
        [ 1.6945e+00,  4.3427e-01,  4.0620e-01, -6.5359e-01,  8.0336e-01],
        [ 3.0135e-01,  3.2478e-01, -9.5046e-01,  1.3796e+00, -9.0188e-01],
        [ 3.1885e-02, -1.4699e+00,  3.6035e-01, -5.5692e-01,  1.1759e+00],
        [-3.3599e-01,  8.5993e-01,  2.3802e-01, -4.2700e-01, -1.8052e+00]])
torch.Size([5, 5]) torch.Size([5, 5])


Size() will give you the tensor dimention. you can also specify the dimention for the size.
According to the following discussion post, `.shape` is an alias for `.size`.
https://github.com/pytorch/pytorch/issues/5544



In [6]:
t = torch.empty(3,4,5)
t.size()
print(t.size(dim = 0),
t.size(dim = 1),
t.size(dim = 2))

3 4 5


In [7]:
t.shape

torch.Size([3, 4, 5])

In [8]:
t.shape[0]

3

When reshaping the tensor, `.view` method is preferred.

In [9]:
matrix = torch.ones((2, 3), dtype=torch.float) 
same_matrix = matrix.view(1,6)

print(matrix)
print(same_matrix)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1.]])


In [10]:
same_matrix[0,1] = 2.

print(matrix)
print(same_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])


The view() do shallow copying, so the two matrices are connected. (that's why is view...?)
Then we swap the value of one, which result in changing the original.

To get a new (deep copied) tensor, use new_tensor() or clone().


In [19]:
# Lets follow PyTorch's suggestion and use "clone" method 
#
another_matrix = matrix.view(1, 6).clone().detach()

In [24]:
another_matrix2 = tensor.new_tensor(matrix.view(1,6))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [21]:
# Again, if we change one of its elements...

another_matrix[0, 1] = 4.

In [25]:
# The original tensor (matrix) is left untouched! 
print(matrix) 
print(another_matrix)
print(another_matrix2)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 4., 1., 1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])


More to come ...! 