In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression

import torch
import torch.optim as optim
import torch.nn as nn
#from torchviz import make_dot

Here are some examples of data.

In [20]:
scalar = torch.tensor(3.14159) 
vector = torch.tensor([1, 2, 3]) 
matrix = torch.ones((2, 3), dtype=torch.float) 
tensor = torch.randn((2, 3, 4), dtype=torch.float)

- [torch.zeros](https://pytorch.org/docs/stable/torch.html)
- [torch.ones](https://pytorch.org/docs/stable/generated/torch.ones.html?highlight=ones#torch.ones)
- [torch.randn](https://pytorch.org/docs/stable/generated/torch.randn.html#torch.randn)
  - randn returns tensor with random values with M = 0 and SD = 1.
- [torch.rand](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand)
  - returns tensor with random values with uniform distribution from 0 to 1.
- [torch.randint](https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint)
  - random integers generated uniformly between low (inclusive) and high (exclusive).



In [ ]:
rand_int = torch.randint(3, 10, (5,5), dtype = torch.int)
print(rand_int)
rand_int = torch.randint(3, 100, (5,5), dtype = torch.int)
print(rand_int)
rand_int = torch.randint(100, 300, (5,5), dtype = torch.int)
print(rand_int)

tensor([[6, 7, 7, 7, 7],
        [7, 8, 5, 3, 6],
        [4, 9, 7, 6, 5],
        [4, 4, 8, 9, 5],
        [4, 3, 3, 9, 3]], dtype=torch.int32)
tensor([[ 6, 35, 96, 36, 45],
        [98, 94, 13, 74, 41],
        [27, 16,  5, 44, 92],
        [21, 53, 75, 42, 76],
        [ 5, 86, 72, 33, 32]], dtype=torch.int32)
tensor([[206, 243, 262, 283, 211],
        [234, 153, 164, 186, 284],
        [280, 211, 211, 253, 152],
        [155, 270, 293, 296, 236],
        [165, 209, 118, 257, 189]], dtype=torch.int32)


In [ ]:
rand = torch.rand((5,5,))
rand

tensor([[0.6888, 0.6345, 0.7345, 0.8218, 0.0045],
        [0.7515, 0.8795, 0.3785, 0.6269, 0.8329],
        [0.9171, 0.4415, 0.2297, 0.2244, 0.1651],
        [0.2104, 0.0374, 0.6378, 0.0534, 0.6843],
        [0.2430, 0.5337, 0.9267, 0.4602, 0.1431]])

In [ ]:
rand_norm = torch.randn((5,5))
print(rand_norm)
print(rand_norm.shape, rand_norm.size())

tensor([[ 0.7296,  0.3313, -0.8852,  0.9852, -0.1820],
        [-0.2483, -0.4155,  0.6138,  0.3305,  1.2802],
        [-0.5143, -1.1479, -2.0366,  1.3654, -1.5237],
        [-1.5687, -0.1161, -1.0506,  1.4330,  0.3043],
        [ 0.4196,  2.1881, -0.6086, -1.3414, -1.1382]])
torch.Size([5, 5]) torch.Size([5, 5])


Size() will give you the tensor dimention. you can also specify the dimention for the size.
According to the following discussion post, `.shape` is an alias for `.size`.
https://github.com/pytorch/pytorch/issues/5544



In [ ]:
t = torch.empty(3,4,5)
t.size()
print(t.size(dim = 0),
t.size(dim = 1),
t.size(dim = 2))

3 4 5


In [ ]:
t.shape

torch.Size([3, 4, 5])

In [ ]:
t.shape[0]

3

When reshaping the tensor, `.view` method is preferred.

In [23]:
matrix = torch.ones((2, 3), dtype=torch.float) 
same_matrix = matrix.view(1,6)

print(matrix)
print(same_matrix)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1., 1.]])


In [24]:
same_matrix[0,1] = 2.

print(matrix)
print(same_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])


The view() do shallow copying, so the two matrices are connected. (that's why is view...?)
Then we swap the value of one, which result in changing the original.

To get a new (deep copied) tensor, use new_tensor() or clone().


More to come ...! 